export const countryMap: Record<string, string> = {
  "polska": "PL",
  "niemcy": "DE",
  "francja": "FR",
  "włochy": "IT",
  "stany zjednoczone": "US",
  "usa": "US",
  "wielka brytania": "GB",
  "anglia": "GB",
  "szwajcaria": "CH",
  "szwecja": "SE",
  "japonia": "JP",
  "korea południowa": "KR",
  "korea": "KR",
  "hiszpania": "ES",
  "holandia": "NL",
  "belgia": "BE",
  "austria": "AT",
  "czechy": "CZ",
  "słowacja": "SK",
  "dania": "DK",
  "finlandia": "FI",
  "norwegia": "NO",
  "chiny": "CN",
  "turcja": "TR",
  "brazylia": "BR",
  "indie": "IN",
  "izrael": "IL",
  "israel": "IL",
  "portugalia": "PT",
  "irlandia": "IE",
  "grecja": "GR",
}

export function getCountryCode(input: string): string | null {
  const normalized = input.toLowerCase().trim()
  return countryMap[normalized] || null
}

export const countryNames: Record<string, string> = {
  "PL": "Polska",
  "DE": "Niemcy",
  "FR": "Francja",
  "IT": "Włochy",
  "US": "USA",
  "GB": "Wielka Brytania",
  "CH": "Szwajcaria",
  "SE": "Szwecja",
  "JP": "Japonia",
  "KR": "Korea Południowa",
  "ES": "Hiszpania",
  "NL": "Holandia",
  "BE": "Belgia",
  "AT": "Austria",
  "CZ": "Czechy",
  "SK": "Słowacja",
  "DK": "Dania",
  "FI": "Finlandia",
  "NO": "Norwegia",
  "CN": "Chiny",
  "TR": "Turcja",
  "BR": "Brazylia",
  "IN": "Indie",
  "IL": "Izrael",
  "PT": "Portugalia",
  "IE": "Irlandia",
  "GR": "Grecja",
  "LU": "Luksemburg",
  "HU": "Węgry",
  "ZA": "RPA",
  "LT": "Litwa",
  "CA": "Kanada",
  "EE": "Estonia",
  "UA": "Ukraina",
  "AU": "Australia",
  "TW": "Tajwan",
  "SI": "Słowenia",
  "HR": "Chorwacja",
}
// Mapa kodów ISO -> polskie nazwy krajów (używana m.in. w alt-ach flag i meta description)
