-- docs/display-names.sql — WYGENEROWANE przez tools/gen-display-name-sql.mjs
-- Wykonaj w Supabase SQL Editor. Ustawia companies.display_name tylko dla marek,
-- ktorych poprawna nazwa rozni sie od auto-generowanej ze sluga (171 firm).
-- Bezpieczne: nie rusza pozostalych firm (fallback na slug daje ten sam wynik).
-- Idempotentne: mozna uruchomic ponownie.

UPDATE companies AS c
SET display_name = v.name
FROM (VALUES
  ('zabka', 'Żabka'),
  ('zywiec-zdroj', 'Żywiec Zdrój'),
  ('grupa-zywiec', 'Grupa Żywiec'),
  ('sniezka', 'Śnieżka'),
  ('tubadzin', 'Tubądzin'),
  ('sokolow', 'Sokołów'),
  ('pszczolka', 'Pszczółka'),
  ('mrowka', 'Mrówka'),
  ('rylko', 'Ryłko'),
  ('wolczanka', 'Wólczanka'),
  ('wisniowski', 'Wiśniowski'),
  ('tarczynski', 'Tarczyński'),
  ('naleczowianka', 'Nałęczowianka'),
  ('cisowianka-naleczow-zdroj', 'Cisowianka Nałęczów Zdrój'),
  ('kopernik-torunskie-pierniki', 'Kopernik Toruńskie Pierniki'),
  ('koleje-dolnoslaskie', 'Koleje Dolnośląskie'),
  ('krajowa-grupa-spozywcza', 'Krajowa Grupa Spożywcza'),
  ('jbb-baldyga', 'JBB Bałdyga'),
  ('madej-wrobel', 'Madej Wróbel'),
  ('meble-wojcik', 'Meble Wójcik'),
  ('osm-lowicz', 'OSM Łowicz'),
  ('osm-piatnica', 'OSM Piątnica'),
  ('piatnica', 'Piątnica'),
  ('osm-ryki', 'OSM Ryki'),
  ('osm-krasnystaw', 'OSM Krasnystaw'),
  ('osm-sierpc', 'OSM Sierpc'),
  ('swiatlowod-inwestycje', 'Światłowód Inwestycje'),
  ('tolpa', 'Tołpa'),
  ('muller', 'Müller'),
  ('bp', 'BP'),
  ('kfc', 'KFC'),
  ('lg', 'LG'),
  ('abb', 'ABB'),
  ('bmw', 'BMW'),
  ('bsh', 'BSH'),
  ('dhl', 'DHL'),
  ('dpd', 'DPD'),
  ('gsk', 'GSK'),
  ('hp', 'HP'),
  ('ibm', 'IBM'),
  ('ing', 'ING'),
  ('jsw', 'JSW'),
  ('msd', 'MSD'),
  ('pge', 'PGE'),
  ('pgnig', 'PGNiG'),
  ('pkp', 'PKP'),
  ('pks', 'PKS'),
  ('pko-bp', 'PKO BP'),
  ('pzu', 'PZU'),
  ('sap', 'SAP'),
  ('sgb', 'SGB'),
  ('tcl', 'TCL'),
  ('tvn', 'TVN'),
  ('ups', 'UPS'),
  ('wp', 'WP'),
  ('ccc', 'CCC'),
  ('lot', 'LOT'),
  ('blik', 'BLIK'),
  ('olx', 'OLX'),
  ('gls', 'GLS'),
  ('ndi', 'NDI'),
  ('cfe', 'CFE'),
  ('dre', 'DRE'),
  ('bps', 'BPS'),
  ('bos', 'BOŚ Bank'),
  ('inea', 'INEA'),
  ('exatel', 'EXATEL'),
  ('rtv-euro-agd', 'RTV EURO AGD'),
  ('usp-zdrowie', 'USP Zdrowie'),
  ('doz-dbam-o-zdrowie', 'DOZ Dbam o Zdrowie'),
  ('tvp-telewizja-polska', 'TVP – Telewizja Polska'),
  ('tui-poland', 'TUI Poland'),
  ('dax-cosmetics', 'DAX Cosmetics'),
  ('pz-cussons-luksja', 'PZ Cussons Luksja'),
  ('jd-sports', 'JD Sports'),
  ('fb-antczak', 'FB Antczak'),
  ('stx-next', 'STX Next'),
  ('dxc-technology', 'DXC Technology'),
  ('epam-systems', 'EPAM Systems'),
  ('bnp-paribas', 'BNP Paribas'),
  ('rmf-fm', 'RMF FM'),
  ('rmf-maxx', 'RMF MAXX'),
  ('tok-fm', 'TOK FM'),
  ('radio-zet', 'Radio ZET'),
  ('h-m', 'H&M'),
  ('c-a', 'C&A'),
  ('s-c-johnson', 'S.C. Johnson'),
  ('tk-maxx', 'TK Maxx'),
  ('max-hbo', 'HBO Max'),
  ('lux-med', 'LUX MED'),
  ('man-man-truck-bus', 'MAN Truck & Bus'),
  ('tiktok', 'TikTok'),
  ('mbank', 'mBank'),
  ('payu', 'PayU'),
  ('paypo', 'PayPo'),
  ('levi-s', 'Levi''s'),
  ('mcdonald-s', 'McDonald''s'),
  ('domino-s-pizza', 'Domino''s Pizza'),
  ('dr-oetker', 'Dr. Oetker'),
  ('dr-max', 'Dr. Max'),
  ('de-longhi', 'De''Longhi'),
  ('loreal', 'L''Oréal'),
  ('coca-cola', 'Coca-Cola'),
  ('pull-bear', 'Pull&Bear'),
  ('procter-gamble', 'Procter & Gamble'),
  ('colgate-palmolive', 'Colgate-Palmolive'),
  ('lindt-sprungli', 'Lindt & Sprüngli'),
  ('estee-lauder', 'Estée Lauder'),
  ('green-caffe-nero', 'Green Caffè Nero'),
  ('nestle', 'Nestlé'),
  ('pepsico', 'PepsiCo'),
  ('mondelez', 'Mondelēz'),
  ('astrazeneca', 'AstraZeneca'),
  ('abbvie', 'AbbVie'),
  ('t-mobile', 'T-Mobile'),
  ('e-on', 'E.ON'),
  ('canal', 'Canal+'),
  ('e-wedel', 'E. Wedel'),
  ('pyszne-pl', 'Pyszne.pl'),
  ('frisco-pl', 'Frisco.pl'),
  ('answear-com', 'Answear.com'),
  ('bonito-pl', 'Bonito.pl'),
  ('taniaksiazka-pl', 'TaniaKsiazka.pl'),
  ('ebilet-pl', 'eBilet.pl'),
  ('cda-pl', 'CDA.pl'),
  ('wakacje-pl', 'Wakacje.pl'),
  ('pracuj-pl-grupa-pracuj', 'Pracuj.pl (Grupa Pracuj)'),
  ('eobuwie-pl', 'eobuwie.pl'),
  ('morele', 'Morele.net'),
  ('cd-projekt-red', 'CD Projekt Red'),
  ('people-can-fly', 'People Can Fly'),
  ('playway', 'PlayWay'),
  ('getresponse', 'GetResponse'),
  ('softserve', 'SoftServe'),
  ('10clouds', '10Clouds'),
  ('11-bit-studios', '11 bit studios'),
  ('neonail', 'NeoNail'),
  ('onlybio', 'OnlyBio'),
  ('yope', 'YOPE'),
  ('4f', '4F'),
  ('seat', 'SEAT'),
  ('skoda', 'Škoda'),
  ('citroen', 'Citroën'),
  ('lego', 'LEGO'),
  ('ikea-sklepy', 'IKEA'),
  ('jysk', 'JYSK'),
  ('obi', 'OBI'),
  ('spar', 'SPAR'),
  ('bricomarche', 'Bricomarché'),
  ('leclerc', 'E.Leclerc'),
  ('media-markt', 'MediaMarkt'),
  ('neonet', 'NEONET'),
  ('kik', 'KiK'),
  ('tedi', 'TEDi'),
  ('halfprice', 'HalfPrice'),
  ('w-kruk', 'W.KRUK'),
  ('yes', 'YES'),
  ('meble-vox', 'Meble VOX'),
  ('polomarket', 'POLOmarket'),
  ('hasco-lek', 'Hasco-Lek'),
  ('enel-med', 'Enel-Med'),
  ('super-pharm', 'Super-Pharm'),
  ('nationale-nederlanden', 'Nationale-Nederlanden'),
  ('unicredit', 'UniCredit'),
  ('uniqa', 'UNIQA'),
  ('ergo-hestia', 'ERGO Hestia'),
  ('millennium', 'Bank Millennium'),
  ('velobank', 'VeloBank'),
  ('nju-mobile', 'nju mobile'),
  ('lajt-mobile', 'lajt.mobile'),
  ('ava-laboratorium', 'AVA Laboratorium')
) AS v(slug, name)
WHERE c.slug = v.slug;

-- Weryfikacja (opcjonalnie):
-- SELECT slug, display_name FROM companies WHERE display_name IS NOT NULL ORDER BY slug;
